name: Cardinal
description: "${description}"
version: "${version}"

main: com.kobosh.cardinal.Cardinal
api-version: '1.21'
folia-supported: true

authors: [ koboshchan ]
website: kobosh.com

depend: [ Quests ]
commands:
  cardinal:
    description: Cardinal admin command
    usage: "/cardinal <init|generate|reload|status>"
